# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - none
variables:
   IISWebsiteName: 'AzureTestProject'

resources:
 pipelines:
     - pipeline: 'buildPipeline'
       project: 'AzureTestProject'
       source: 'Build pipeline'
       branch: 'main'

stages:
    - stage: Deploywebsite
      displayName: 'Deploy website'
      pool: 
        vmImage: ubuntu-latest
    
      
      jobs:
        - deployment: Deploywebsite
             displayname:'Deploy website'
             #environment: 'windows 11 server.DAVE'
             strategy:
              runonce:
                deploy:
                 steps:
                   - checkout : none

                   - download: 'buildPipeline'
                     name: 'DownloadBuildArtefacts'
                     displayname: 'Download Build Artefacts'
                     artefact: 'AzureTestProject'
                     
                   - task: IISWebAppManagementOnMachineGroup@0
                     name: StopIIS
                     displaName: 'Stop IIS website'
                     inputs:
                        IISDeploymentType: 'IISWebsite'
                        ActionIISWebsite: 'StopWebsite'
                        StartStopWebsiteName: '${{variables.IISWebsiteName}}'
                        
                   - script: echo $(Pipeline.Workspace)\buildPipeline\AzureTestProject\RoundTheCode.AzureTestProject
                   - task: IISWebAppDeploymentOnMachineGroup@0
                     name: 'DeployIIS'
                     displayName: 'Deploy IIS website' 
                     inputs:
                        WebSiteName: '''${{variables.IISWebsiteName}}'''
                        Package: '$(Pipeline.Workspace)\buildPipeline\AzureTestProject\RoundTheCode.AzureTestProject'
                        TakeAppOfflineFlag: true
                    
                   - task: IISWebAppManagementOnMachineGroup@0
                     name: 'StartIIS'
                     displayName: 'Start IIS website'                     
                     inputs:
                      IISDeploymentType: 'IISWebsite'
                      ActionIISWebsite: 'StartWebsite'
                      StartStopWebsiteName: '${{ variables.IISWebsiteName }}'

         